# En→Fr：词表 32000（参考论文）
model:
  N: 6
  d_model: 512
  d_ff: 2048
  num_heads: 8
  dropout: 0.1
  activation: "relu"
  pos_encoding: "sinusoidal"
  label_smoothing: 0.1
  vocab_size: 32000

data:
  dataset: "wmt14"
  lang_pair: "en-fr"
  tokenizer_dir: "work/tokenizer_en_fr"
  vocab_size: 32000
  max_tokens_per_batch: 50000
  num_buckets: 8

optim:
  warmup_steps: 4000
  max_steps: 100000

runtime:
  log_dir: "work/logs_en_fr_base"
  ckpt_dir: "work/checkpoints_en_fr_base"
  tb_dir: "work/tb_en_fr_base"
